{
 "title": "Flight Track Testboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "flight",
    "label": "Flight(s): ",
    "query": {
     "query": "label_values(point_list{id!=\"$null_ptr\"},id)"
    }
   },
   { "name": "null_ptr" }
  ]
 },
 "panels": [
  { "title": "Global Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GeoMap",
   "type": "geomap",
   "gridPos": { "h": 22, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "point_list", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Flight Altitude Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 8, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "point_list{type=\"hei\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Tracking #",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "point_list{type=\"hei\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Altitudes by Flight",
   "type": "stat",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "expr": "point_list{type=\"hei\"}",
     "legendFormat": "Id: {{id}}"
    }
   ]
  },
  {
   "title": "Distribution speed over altitude",
   "type": "xychart",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 23 },
   "targets": [
    { "expr": "point_list", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Altitudes",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 22, "w": 13, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    { "expr": "point_list", "legendFormat": "{{id}}" }
   ]
  },
  {
   "title": "Airspeed to Altitude Relation over Flights",
   "type": "trend",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 33 },
   "targets": [
    { "expr": "point_list", "legendFormat": "__auto" }
   ]
  },
  { "title": "Flight $flight visualization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }, "repeat": "flight" },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 7, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Altitude Groupings",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\", type=\"hei\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airspeed Groupings",
   "type": "state-timeline",
   "gridPos": { "h": 3, "w": 8, "x": 11, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\", type=\"spd\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "GeoMap",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 11, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "point_list{id=\"$flight\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "lengthft" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\", type=\"hei\"}",
     "legendFormat": "Id: {{id}}"
    }
   ]
  },
  {
   "title": "Airspeed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\", type=\"spd\"}",
     "legendFormat": "Id: {{id}}"
    }
   ]
  },
  {
   "title": "Rate of Climb",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "ft/m" } },
   "targets": [
    {
     "expr": "point_list{id=\"$flight\", type=\"roc\"}",
     "legendFormat": "Id: {{id}}"
    }
   ]
  }
 ]
}