 global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 10s

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - java:19501